package com.cmos.chopmkactivity.iservice.dept;

import com.cmos.chopmkactivity.beans.dept.Dept;

import java.util.List;

public interface IDeptSV {

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table dept
     *
     * @date 2016-11-28 11:00:11
     */
    int deleteByPrimaryKey(Long parameterId);

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table dept
     *
     * @date 2016-11-28 11:00:11
     */
    int insert(Dept record);

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table dept
     *
     * @date 2016-11-28 11:00:11
     */
    Dept getByPrimaryKey(Long parameterId);

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table dept
     *
     * @date 2016-11-28 11:00:11
     */
    int updateByPrimaryKey(Dept record);

    /**
     * 以部门名称查询部门信息
     * @param dname 部门名称
     * @return 部门信息
     */
    Dept getByDname(String dname);
}
