package com.cmos.chopmkactivity.iservice.emp;

import com.cmos.chopmkactivity.beans.emp.Emp;

import java.math.BigDecimal;
import java.util.List;

/**
 * Demo示例,员工信息服务接口
 *
 * @author zhuanghd
 * @since 1.0
 */
public interface IEmpSV {

    /**
     * 分页查询
     * @param pageNum 页码
     * @param pageSize 每页的大小
     * @return 员工对象列表
     */
    List<Emp> getByPage(Integer pageNum, Integer pageSize);


    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table EMP
     *
     * @date 2016-11-16 16:13:30
     */
    int deleteByPrimaryKey(Long parameterId);

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table EMP
     *
     * @date 2016-11-16 16:13:30
     */
    int insert(Emp record);

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table EMP
     *
     * @date 2016-11-16 16:13:30
     */
    Emp getByPrimaryKey(Long parameterId);

    /**
     * This method was generated by IDE Plugin.
     * This method corresponds to the database table EMP
     *
     * @date 2016-11-16 16:13:30
     */
    int updateByPrimaryKey(Emp record);

    /**
     * 按照部门统计员工总数
     * @param deptno 部门编号
     * @return 员工总数
     */
    int countByDeptno(BigDecimal deptno);
}
